<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<Authors>Mansoor Omrani</Authors>
		<Company>PuyaSoft</Company>
		<Product>Puya.NET</Product>
		<Version>4.13.1</Version>
		<WebPage>https://puyasoft.com</WebPage>
		<PackageProjectUrl>https://github.com/puyacodes/Puya.NET</PackageProjectUrl>
		<AppxAutoIncrementPackageRevision>True</AppxAutoIncrementPackageRevision>
		<SignAssembly>False</SignAssembly>
		<AssemblyOriginatorKeyFile>../snk.pfx</AssemblyOriginatorKeyFile>
		<AssemblyVersion>4.13.1.0</AssemblyVersion>
		<Nullable>disable</Nullable>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<Copyright>2018-2025</Copyright>
		<RepositoryType>https://github.com/puyacodes/Puya.NET</RepositoryType>
		<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<RepositoryUrl>https://github.com/puyacodes/Puya.NET</RepositoryUrl>
		<PackageTags>Puyasoft, Tap, Tarh Andishan Puya, Puya.Net, .Net</PackageTags>
		<PackageReleaseNotes>This is the first public release of Puya.NET package.</PackageReleaseNotes>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\LICENSE.txt" Pack="true" PackagePath="LICENSE.txt" />
		<None Include="..\README.md" Pack="true" PackagePath="README.md" />
	</ItemGroup>

	<ItemGroup>
		<Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
	</ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
		<PackageReference Include="Hangfire.Core" Version="1.8.14" />
		<PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.0.0" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.0.0" />
		<PackageReference Include="UAParser" Version="3.1.47" />
		<PackageReference Include="Puya.Core" Version="3.13.1" />
	</ItemGroup>

</Project>
